name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Package and Upload Zip Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP file
        working-directory: ./custom_components/geberit_toilet
        run: |
          zip geberit_toilet.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./custom_components/geberit_toilet/geberit_toilet.zip
