name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Package and Upload Zip Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          cd custom_components
          zip -r ../geberit_toilet.zip geberit_toilet

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: geberit_toilet.zip
